-- CREATE TABLE booking(id SERIAL PRIMARY KEY, user_id VARCHAR(100) NOT NULL, space_id INTEGER NOT NULL, date VARCHAR(60) NOT NULL); 
CREATE TABLE booking(id SERIAL PRIMARY KEY, user_id VARCHAR(100) NOT NULL, space_id INTEGER NOT NULL, date VARCHAR(60) NOT NULL, requests VARCHAR(20) DEFAULT 'Pending');
